### ISSUE TITLE
Issue from #1113

### ISSUE THREAD

**Issue by vooku** [vooku/tvaem#10]
## ideas
- [x] nastavit u videa jestli má pokračovat nebo trigrovat vždycky od začátku
- [x] do video dialogu dat cislo vrstvy
- [ ] save and save as https://github.com/vooku/tvaem/issues/20
- [x] log fps
- [ ] make effects global https://github.com/vooku/tvaem/issues/19

## issues
- [x] ~config only possible to save into data folder~
- [ ] cut off letter boxing https://github.com/vooku/tvaem/issues/21
- [x] cannot load config specified in cmd arguments
